repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ "--fix", "--show-fixes" ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
    - id: remove-tabs
      exclude: ^(docs)
