[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "meter"
version = "0.0.1"
dependencies = [
]
requires-python = ">=3.12"
description = "Package to supervised learning on meter data"


[tool.hatch.build.targets.wheel]
packages = ["src/meter"]